### ISSUE TITLE
testing 1st release

### ISSUE THREAD

**Issue by hoseyjoe** [core-haxe/sqlite3#1]
Only see race("hi3");
[testsql.zip](https://github.com/core-haxe/sqlite3/files/10415399/testsql.zip)

**Comment by ianharrigan** [comment]
Thats a strange one, so the first issue is the sql that you copy and pasted from the read me is wrong (fixing that now), but there is something else going on with the native sql cache... something really weird... i might just remove it...

**Comment by ianharrigan** [comment]
haha, ok, the database hadnt been opened - still that wasnt obvious... ill patch that to make it clearer

**Comment by ianharrigan** [comment]
Alright, this should be fixed now:

1) Fixed the sql in the readme
2) Added the "open" call in the readme
3) If the db isnt open, then it will throw an error (rather than just fail in an obscure way)

Lemme know if that works your end, and if it does, can you close this?
